# Generated by Django 5.2.7 on 2025-10-16 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEquipo',
            fields=[
                ('id_estado_equipo', models.AutoField(db_column='ID_EstadoEquipo', primary_key=True, serialize=False)),
                ('nom_estado', models.CharField(db_column='Nom_Estado', max_length=50)),
            ],
            options={
                'verbose_name': 'Estado de Equipo',
                'verbose_name_plural': 'Estados de Equipo',
                'db_table': 'Tb_ESTADO_EQUIPO',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(db_column='ID_Equipo', primary_key=True, serialize=False)),
                ('nom_equipo', models.CharField(db_column='Nom_Equipo', max_length=10)),
                ('num_serie', models.CharField(db_column='Num_Serie', max_length=50, unique=True)),
                ('modelo', models.CharField(db_column='Modelo', max_length=50)),
                ('id_rack', models.ForeignKey(blank=True, db_column='ID_Rack', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rack')),
                ('id_estado_equipo', models.ForeignKey(db_column='ID_EstadoEquipo', on_delete=django.db.models.deletion.PROTECT, to='Gestion_Equipos.estadoequipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'Tb_EQUIPO',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(db_column='ID_Reserva', primary_key=True, serialize=False)),
                ('fecha_uso', models.DateField(db_column='Fecha_Uso')),
                ('hora_inicio', models.TimeField(db_column='Hora_Inicio')),
                ('hora_fin', models.TimeField(db_column='Hora_Fin')),
                ('cant_solicitada', models.IntegerField(db_column='Cant_Solicitada')),
                ('estado_reserva', models.CharField(db_column='Estado_Reserva', max_length=20)),
                ('id_asignatura', models.ForeignKey(db_column='ID_Asignatura', on_delete=django.db.models.deletion.CASCADE, to='core.asignatura')),
                ('id_aula', models.ForeignKey(db_column='ID_Aula', on_delete=django.db.models.deletion.CASCADE, to='core.aula')),
                ('id_carrera', models.ForeignKey(db_column='ID_Carrera', on_delete=django.db.models.deletion.CASCADE, to='core.carrera')),
                ('id_usuario', models.ForeignKey(db_column='ID_Usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'Tb_RESERVA',
            },
        ),
        migrations.CreateModel(
            name='AsignacionEquipo',
            fields=[
                ('id_asig_equipo', models.AutoField(db_column='ID_AsigEquipo', primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='Fecha_Registro')),
                ('id_equipo', models.ForeignKey(db_column='ID_Equipo', on_delete=django.db.models.deletion.CASCADE, to='Gestion_Equipos.equipo')),
                ('id_reserva', models.ForeignKey(db_column='ID_Reserva', on_delete=django.db.models.deletion.CASCADE, to='Gestion_Equipos.reserva')),
            ],
            options={
                'verbose_name': 'Asignación de Equipo',
                'verbose_name_plural': 'Asignaciones de Equipos',
                'db_table': 'Tb_ASIGNACION_EQUIPO',
                'unique_together': {('id_reserva', 'id_equipo')},
            },
        ),
    ]
