# Generated by Django 5.2.7 on 2025-10-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='responsable_entrega',
            field=models.CharField(db_column='Responsable_Entrega', default='', help_text='Nombre del responsable de recibir los equipos', max_length=150),
        ),
        migrations.AddField(
            model_name='reserva',
            name='telefono_contacto',
            field=models.CharField(db_column='Telefono_Contacto', default='', help_text='Teléfono de contacto del responsable', max_length=10),
        ),
    ]
