# Generated by Django 5.2.7 on 2025-11-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Equipos', '0002_reserva_responsable_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='motivo_rechazo',
            field=models.TextField(blank=True, db_column='Motivo_Rechazo', help_text='Motivo por el cual se rechazó la reserva', null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado_reserva',
            field=models.CharField(db_column='Estado_Reserva', default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='responsable_entrega',
            field=models.CharField(db_column='Responsable_Entrega', help_text='Nombre del responsable de recibir los equipos', max_length=150),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefono_contacto',
            field=models.CharField(db_column='Telefono_Contacto', help_text='Teléfono de contacto del responsable', max_length=10),
        ),
    ]
