# Generated by Django 5.2.7 on 2025-11-08 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Equipos', '0003_reserva_motivo_rechazo_alter_reserva_estado_reserva_and_more'),
        ('core', '0006_asignatura_id_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, db_column='Fecha_Devolucion', help_text='Fecha y hora de devolución de equipos', null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, db_column='Fecha_Entrega', help_text='Fecha y hora de entrega de equipos', null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='observaciones',
            field=models.TextField(blank=True, db_column='Observaciones', help_text='Observaciones durante el préstamo', null=True),
        ),
        migrations.CreateModel(
            name='EvidenciaReserva',
            fields=[
                ('id_evidencia', models.AutoField(db_column='ID_Evidencia', primary_key=True, serialize=False)),
                ('tipo_evidencia', models.CharField(choices=[('uso', 'Uso de Equipos'), ('devolucion', 'Devolución de Equipos')], db_column='Tipo_Evidencia', max_length=20)),
                ('foto', models.ImageField(db_column='Foto', help_text='Fotografía de evidencia', upload_to='evidencias/')),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', help_text='Descripción de la evidencia', null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, db_column='Fecha_Subida')),
                ('id_reserva', models.ForeignKey(db_column='ID_Reserva', on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='Gestion_Equipos.reserva')),
            ],
            options={
                'verbose_name': 'Evidencia de Reserva',
                'verbose_name_plural': 'Evidencias de Reservas',
                'db_table': 'Tb_EVIDENCIA_RESERVA',
            },
        ),
        migrations.CreateModel(
            name='SupervisorReserva',
            fields=[
                ('id_supervisor_reserva', models.AutoField(db_column='ID_SupervisorReserva', primary_key=True, serialize=False)),
                ('id_reserva', models.ForeignKey(db_column='ID_Reserva', on_delete=django.db.models.deletion.CASCADE, related_name='supervisores', to='Gestion_Equipos.reserva')),
                ('id_supervisor', models.ForeignKey(db_column='ID_Supervisor', limit_choices_to={'id_tipo_usuario__nom_rol': 'Supervisor'}, on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'verbose_name': 'Supervisor de Reserva',
                'verbose_name_plural': 'Supervisores de Reserva',
                'db_table': 'Tb_SUPERVISOR_RESERVA',
                'unique_together': {('id_reserva', 'id_supervisor')},
            },
        ),
    ]
