# Generated by Django 5.2.7 on 2025-10-16 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(db_column='ID_Asignatura', primary_key=True, serialize=False)),
                ('nom_asignatura', models.CharField(db_column='Nom_Asignatura', max_length=50)),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'db_table': 'Tb_ASIGNATURA',
            },
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id_bloque', models.AutoField(db_column='ID_Bloque', primary_key=True, serialize=False)),
                ('nom_bloque', models.CharField(db_column='Nom_Bloque', max_length=30)),
            ],
            options={
                'verbose_name': 'Bloque',
                'verbose_name_plural': 'Bloques',
                'db_table': 'Tb_BLOQUE',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.AutoField(db_column='ID_Facultad', primary_key=True, serialize=False)),
                ('nom_facultad', models.CharField(db_column='Nom_Facultad', max_length=100)),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'db_table': 'Tb_FACULTAD',
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id_rack', models.AutoField(db_column='ID_Rack', primary_key=True, serialize=False)),
                ('nom_rack', models.CharField(db_column='Nom_Rack', max_length=10)),
                ('ubicacion', models.CharField(db_column='Ubicacion', max_length=50)),
                ('capacidad_total', models.IntegerField(db_column='Capacidad_Total')),
                ('capacidad_func', models.IntegerField(db_column='Capacidad_Func')),
                ('estado_rack', models.CharField(db_column='Estado_Rack', max_length=20)),
            ],
            options={
                'verbose_name': 'Rack',
                'verbose_name_plural': 'Racks',
                'db_table': 'Tb_RACK',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(db_column='ID_TipoUsuario', primary_key=True, serialize=False)),
                ('nom_rol', models.CharField(db_column='Nom_Rol', max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Usuario',
                'verbose_name_plural': 'Tipos de Usuario',
                'db_table': 'Tb_TIPO_USUARIO',
            },
        ),
        migrations.CreateModel(
            name='TituloProfesional',
            fields=[
                ('id_titulo', models.AutoField(db_column='ID_Titulo', primary_key=True, serialize=False)),
                ('nom_titulo', models.CharField(db_column='Nom_Titulo', max_length=50)),
            ],
            options={
                'verbose_name': 'Título Profesional',
                'verbose_name_plural': 'Títulos Profesionales',
                'db_table': 'Tb_TITULO_PROFESIONAL',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id_aula', models.AutoField(db_column='ID_Aula', primary_key=True, serialize=False)),
                ('nom_aula', models.CharField(db_column='Nom_Aula', max_length=30)),
                ('id_bloque', models.ForeignKey(db_column='ID_Bloque', on_delete=django.db.models.deletion.CASCADE, to='core.bloque')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'db_table': 'Tb_AULA',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(db_column='ID_Carrera', primary_key=True, serialize=False)),
                ('nom_carrera', models.CharField(db_column='Nom_Carrera', max_length=100)),
                ('id_facultad', models.ForeignKey(db_column='ID_Facultad', on_delete=django.db.models.deletion.PROTECT, to='core.facultad', verbose_name='Facultad')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'db_table': 'Tb_CARRERA',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='ID_Usuario', primary_key=True, serialize=False)),
                ('nom_completo', models.CharField(db_column='Nom_Completo', max_length=150)),
                ('cedula', models.CharField(db_column='Cedula', max_length=10, unique=True)),
                ('telefono', models.CharField(db_column='Telefono', max_length=10)),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('id_tipo_usuario', models.ForeignKey(db_column='ID_TipoUsuario', on_delete=django.db.models.deletion.PROTECT, to='core.tipousuario')),
                ('id_titulo', models.ForeignKey(blank=True, db_column='ID_Titulo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tituloprofesional')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Tb_USUARIO',
            },
        ),
        migrations.CreateModel(
            name='DocenteCarrera',
            fields=[
                ('id_docente_carrera', models.AutoField(db_column='ID_DocenteCarrera', primary_key=True, serialize=False)),
                ('id_carrera', models.ForeignKey(db_column='ID_Carrera', on_delete=django.db.models.deletion.CASCADE, to='core.carrera')),
                ('id_usuario', models.ForeignKey(db_column='ID_Usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'verbose_name': 'Docente-Carrera',
                'verbose_name_plural': 'Docentes-Carreras',
                'db_table': 'Tb_DOCENTE_CARRERA',
                'unique_together': {('id_usuario', 'id_carrera')},
            },
        ),
    ]
