# Generated by Django 5.2.7 on 2025-10-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(db_column='Username', default='', help_text='Nombre de usuario para login', max_length=10, unique=True),
        ),
    ]
