# Generated by Django 5.2.7 on 2025-10-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(db_column='Password', default='', help_text='Contraseña encriptada', max_length=255),
            preserve_default=False,
        ),
    ]
