# Generated by Django 5.2.7 on 2025-10-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(db_column='Username', help_text='Nombre de usuario para login', max_length=10, unique=True),
        ),
    ]
