# Generated by Django 5.2.7 on 2025-10-21 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='id_facultad',
            field=models.ForeignKey(db_column='ID_Facultad', on_delete=django.db.models.deletion.CASCADE, to='core.facultad', verbose_name='Facultad'),
        ),
    ]
