# Generated by Django 5.2.7 on 2025-10-22 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_carrera_id_facultad'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='id_carrera',
            field=models.ForeignKey(db_column='ID_Carrera', default=1, help_text='Carrera a la que pertenece esta asignatura', on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='core.carrera'),
            preserve_default=False,
        ),
    ]
